# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Gorseller/car-rental-social-media-thumbnail-template-flat-cartoon-background-illustration-vector.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuSe_enekler = QtWidgets.QMenu(self.menubar)
        self.menuSe_enekler.setObjectName("menuSe_enekler")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionArac_Menu = QtWidgets.QAction(MainWindow)
        self.actionArac_Menu.setObjectName("actionArac_Menu")
        self.actionMusteri_Menu = QtWidgets.QAction(MainWindow)
        self.actionMusteri_Menu.setObjectName("actionMusteri_Menu")
        self.actionKiralama_Menu = QtWidgets.QAction(MainWindow)
        self.actionKiralama_Menu.setObjectName("actionKiralama_Menu")
        self.menuSe_enekler.addAction(self.actionArac_Menu)
        self.menuSe_enekler.addSeparator()
        self.menuSe_enekler.addAction(self.actionMusteri_Menu)
        self.menuSe_enekler.addSeparator()
        self.menuSe_enekler.addAction(self.actionKiralama_Menu)
        self.menuSe_enekler.addSeparator()
        self.menubar.addAction(self.menuSe_enekler.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sevinc Car "))
        self.menuSe_enekler.setTitle(_translate("MainWindow", "Seçenekler"))
        self.actionArac_Menu.setText(_translate("MainWindow", "Arac Menu"))
        self.actionMusteri_Menu.setText(_translate("MainWindow", "Musteri Menu"))
        self.actionKiralama_Menu.setText(_translate("MainWindow", "Kiralama Menu"))
